export const PRODUCTS = [
  {
    id: 'nanas-glazed-joy',
    name: "Nana's Glazed Joy",
    flavor: 'Double Glazed & Sprinkles',
    sweetness: 'High',
    sweetnessRating: 4,
    size: 'Regular',
    price: 3.50,
    category: 'donut',
    isBestSeller: true,
    img: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDhHBd4vf49z6RkPt_GmDWQcvpn2-oeLRFv_DQxAp8w9kFT6dDnbH4kz8H-msL9GdhAtoRjliudbnlBIENxvm9Wh9la0ni6E_2QDDwnEKEfbdbF-jQk0yWjqYy2cy2uGypw4TSoWknXj_aGAad2XrXpOFsurvauLSY46E7NiM1tFCeKny_z2YAKG8HchvqKfhBVdtBYLMYeaU6ds0lamj1-d8pmY9Rv1jBHpmGwBYEbyNAPe6kVA3RucwXp0cgFkTvUw3SuBhzWOqc',
    description: 'Donas extra esponjosas con doble glaseado de vainilla y chispas de colores nostálgicos. Elaboradas según la icónica receta familiar para evocar dulces mañanas de domingo.',
    ingredients: ['Harina de trigo orgánica', 'Vino blanco dulce de la abuela', 'Suero de leche fresco', 'Extracto puro de vainilla de Madagascar', 'Chispas de azúcar confitadas']
  },
  {
    id: 'cloud-nine-macarons',
    name: 'Cloud Nine Macarons',
    flavor: 'Vanilla & Almond',
    sweetness: 'Medium',
    sweetnessRating: 3,
    size: 'Mini',
    price: 5.50,
    category: 'macaron',
    isStaffPick: true,
    img: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCueKc2ExOuni2DNUIKchzynUirXBSdNnSNSUEip2I5b03H3wdvPoKc0M852SHOv3zKcKH1Q-jpOw2f8DK6Hh3MuWgJLr-YziPk-eOF2Fuq21NG8x_hAOon84f-NP7mW3TJoeOq1rA-IlnorZDKnShPRWs9TP8wrDnbQCDXH8nQFC1TSvIn4wLv4C0Y9D5tUjtxkp6_7i3YC6ZbGY1H6GokeZ9JNysRhw_dxiifJ6cEXLrvI0MJ04baJ-PuwWWDTxBh-Hx0jbRwsjM',
    description: 'Bocados celestiales de merengue de almendra con texturas perfectamente equilibradas: crujiente por fuera, tierno por dentro. Rellenos con crema suave de vainilla.',
    ingredients: ['Harina de almendra fina', 'Claras de huevo de pastoreo', 'Azúcar glass', 'Mantequilla artesanal pomada', 'Vainilla en rama de Papantla']
  },
  {
    id: 'velvet-memory-cupcake',
    name: 'Velvet Memory Cupcake',
    flavor: 'Chocolate Cherry',
    sweetness: 'High',
    sweetnessRating: 4,
    size: 'Regular',
    price: 4.20,
    category: 'cupcake',
    isFanFavorite: true,
    img: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCxZPp9vETDyUKG3ieyWefdb_tF_0ZwEqTMcUfCGOPXKv6MIuV9StK5e2MeLXugpohdFXxAw9M-bfONdv-6N06SpKSf2T7ca4LnSCSF-4tiUsXB4tNTmVgUGLi5KJB5qXpwID2WIy6WwdL412DdDDOAbOiqPuLDH_wA0OV9idMI_IDMBU71c7slFMIeSO-70bLM58waFLGSmPbETomqyxUvY7tZECRGf-G-TWXgL3B0pIqPYBYVexy5qwmQD6cHrpGIA4AlyJNUFAQ',
    description: 'Magdalena premium de cacao belga cubierto con un majestuoso espiral de frosting aterciopelado de fresa y coronado con una jugosa cereza en almíbar.',
    ingredients: ['Cacao belga alcalinizado al 70%', 'Cerezas de la Patagonia', 'Mantequilla de granja', 'Queso crema batido', 'Harina de repostería tamizada']
  },
  {
    id: 'zesty-sunshine-tart',
    name: 'Zesty Sunshine Tart',
    flavor: 'Lemon & Cream',
    sweetness: 'Medium',
    sweetnessRating: 3,
    size: 'Regular',
    price: 4.80,
    category: 'tart',
    isBestSeller: true,
    img: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBynnAPqKGZRN2chbprUEWzWO9d2eUOxrwtpZm_cNkox5CALx1GZ8G9aR8v-I8TAClpas6z7Of4vYqO6a88WUAdhzJiuP9x0nJWIVIJd7AY4TOZEAQCH95G8QIzG5-BERern-KruQ8HsI3d_SrWnlQWr9Glto1CYzT7-YwKnd2Pz5ibjl8k1sk7BQb8eXu8thZ4Gjhx6QsMLhUjg14t__hKqGE6dssmUX7OW1CLnUL150fnTauaNwzhbDIGzJcbqM2_OJBpOzIiTL8',
    description: 'Tarta luminosa de limón sobre una costra crujiente de galletas Graham caseras. Coronado con ralladura confitada y menta de nuestro huerto.',
    ingredients: ['Limones amarillos ecológicos', 'Galletas Graham hechas en casa', 'Mantequilla tostada', 'Huevos ecológicos', 'Crema entera de rancho', 'Hojas de menta']
  },
  {
    id: 'strawberry-dream',
    name: 'Strawberry Dream',
    flavor: 'Berry Bliss',
    sweetness: 'High',
    sweetnessRating: 4,
    size: 'Mini',
    price: 5.95,
    category: 'cake',
    img: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=500',
    description: 'Bizcocho esponjoso empapado artesanalmente, alternado con capas de fresas frescas maceradas y crema batida ligera que se deshace en la boca.',
    ingredients: ['Fresas silvestres enteras', 'Harina de trigo fina', 'Crema de leche batida a mano', 'Azúcar rubia de caña', 'Toque de ron añejo de repostería']
  },
  {
    id: 'choco-classic',
    name: 'Choco Classic',
    flavor: 'Dark Cocoa',
    sweetness: 'Medium',
    sweetnessRating: 3,
    size: 'Regular',
    price: 6.20,
    category: 'cake',
    img: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500',
    description: 'Pastel de chocolate belga tradicional de gran densidad, cubierto de ganache oscuro lustroso de aspecto clásico e irresistible.',
    ingredients: ['Chocolate negro 65% de origen único', 'Manteca pura de cacao', 'Crema para batir fresca', 'Huevos orgánicos enteros', 'Polvo de café espresso para realzar el cacao']
  },
  {
    id: 'vanilla-bean',
    name: 'Vanilla Bean',
    flavor: 'Pure Cream',
    sweetness: 'Low',
    sweetnessRating: 2,
    size: 'Regular',
    price: 4.10,
    category: 'cupcake',
    img: 'https://images.unsplash.com/photo-1550617931-e17a7b70dce2?w=500',
    description: 'La delicadeza absoluta: cupcake esponjoso de vainilla natural moteado con semillas genuinas de vaina de vainilla y coronado con crema de mantequilla tierna.',
    ingredients: ['Semillas de vainilla Bourbon auténticas', 'Pellejo de vainilla molida', 'Leche entera fresca', 'Harina repostera blanca', 'Sal marina gruesa un toque']
  },
  {
    id: 'blueberry-hill',
    name: 'Blueberry Hill',
    flavor: 'Wild Berry',
    sweetness: 'Medium',
    sweetnessRating: 3,
    size: 'Large',
    price: 6.50,
    category: 'tart',
    img: 'https://images.unsplash.com/photo-1519915028121-7d3463d20b13?w=500',
    description: 'Pie de arándanos silvestres con una rejilla de hojaldre crujiente dorada al horno. El relleno es un almíbar asombroso de frutos del bosque.',
    ingredients: ['Arándanos negros silvestres', 'Pasta brisa clásica de mantequilla', 'Cáscara de naranja orgánica rallada', 'Maicena artesanal', 'Azúcar perlada para el exterior']
  },
  {
    id: 'honey-bee',
    name: 'Honey Bee',
    flavor: 'Golden Nectar',
    sweetness: 'High',
    sweetnessRating: 4,
    size: 'Mini',
    price: 4.90,
    category: 'other',
    img: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=500',
    description: 'Crepas dobladas artesanalmente con queso ricotta batido, miel de abeja multifloral pura y nueces pecanas tostadas.',
    ingredients: ['Miel de abeja de monte virgen', 'Queso ricotta artesanal suave', 'Nueces pacanas ecológicas', 'Harina batida a mano', 'Toque de cardamomo molido']
  },
  {
    id: 'pink-velvet',
    name: 'Pink Velvet',
    flavor: 'Rose & Cream',
    sweetness: 'Medium',
    sweetnessRating: 3,
    size: 'Mini',
    price: 4.50,
    category: 'cupcake',
    img: 'https://images.unsplash.com/photo-1519869325930-281384150729?w=500',
    description: 'Una variación jugosa y rosada con un sutil infusionado de pétalos de rosa y una base esponjosa de bizcocho esponjoso con crema aterciopelada.',
    ingredients: ['Extracto natural de pétalos de rosa destilado', 'Colorante natural de betabel', 'Mantequilla batida', 'Queso Mascarpone tierno', 'Harina fina']
  },
  {
    id: 'matcha-mist',
    name: 'Matcha Mist',
    flavor: 'Earth Leaf',
    sweetness: 'Low',
    sweetnessRating: 2,
    size: 'Regular',
    price: 5.20,
    category: 'cake',
    img: 'https://images.unsplash.com/photo-1536184071535-78906f7172c2?w=500',
    description: 'Bizcocho esponjoso y cremoso de té verde Matcha ceremonial japonés balanceado con capas delgadas de judía dulce azuki artesanal.',
    ingredients: ['Té verde matcha premium Uji', 'Judías rojas de soya dulce', 'Harina de arroz y trigo', 'Leche de coco cremosa', 'Azúcar moscabado de caña']
  },
  {
    id: 'caramel-twist',
    name: 'Caramel Twist',
    flavor: 'Burnt Sugar',
    sweetness: 'Extreme',
    sweetnessRating: 5,
    size: 'Large',
    price: 5.80,
    category: 'tart',
    img: 'https://images.unsplash.com/photo-1464305795204-6f5bdf7ad73a?w=500',
    description: 'Exuberante tarta rellena con caramelo salado a la mantequilla tostada, coronada con crema batida doble y un remolino de salsa de caramelo.',
    ingredients: ['Azúcar morena caramelizada', 'Mantequilla con sal marina pura', 'Flor de sal en escamas', 'Pasta azucarada fina crujiente', 'Crema espesa de rancho']
  },
  {
    id: 'lemon-drop',
    name: 'Lemon Drop',
    flavor: 'Citrus Fizz',
    sweetness: 'Medium',
    sweetnessRating: 3,
    size: 'Mini',
    price: 3.80,
    category: 'cupcake',
    img: 'https://images.unsplash.com/photo-1519058023233-568134bc0096?w=500',
    description: 'Mini cupcake esponjoso con un corazón líquido de lemon curd súper zesty, coronado con una corona crujiente de merengue suizo dorado.',
    ingredients: ['Zumo puro de limas frescas', 'Yemas de huevo de corral', 'Mantequilla cremosa de rumiante', 'Claras montadas a punto de nieve', 'Ralladura cítrica fina']
  },
  {
    id: 'peach-fuzz',
    name: 'Peach Fuzz',
    flavor: 'Soft Fruit',
    sweetness: 'Low',
    sweetnessRating: 2,
    size: 'Regular',
    price: 4.60,
    category: 'tart',
    img: 'https://images.unsplash.com/photo-1557089706-68d02dbda277?w=500',
    description: 'Tartaleta rústica campesina rellena de gajos de melocotón de temporada asados al horno con un toque de canela fresca y mantequilla tamizada.',
    ingredients: ['Melocotones amarillos tiernos', 'Masa de hojaldre artesanal', 'Canela en rama molida', 'Azúcar de caña en bruto', 'Brandy reposado un toque']
  }
];

export const INITIAL_REVIEWS = [
  {
    id: 'review-1',
    name: 'Clara M.',
    findUsMethod: "Friend's recommendation",
    triedProduct: 'Strawberry Dream',
    sweetnessRating: 4,
    comment: '¡El Strawberry Dream me transportó de inmediato a mi fiesta de cumpleaños número 8! Casi podía escuchar la música y ver las guirnaldas. Es increíblemente tierno, fresco y lleno de sabor nostálgico.',
    imageFile: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAmalNjOkJyARsRzTAlNDD1eSiRaGBMidwHd-vbkGvXABLkd_d__04-4DUGgPOjMQgBlRePGT_t5Kb2Jw0FKWHsqW9bsnYJiWSUdg35sawnehI3V7LcazwVrCnjq7sRDOmJfY4PdROOEKYkNjx___u13lOTjwpxVWtnhlZlkBsGQDwQoPekoYgymUPRn7mFm52TKEVKUolkvRfj-81MbsXLHfonGGA58zYZWEtsELtmuDKxcjIgiuMw04ZNm4qEI4L5zTWT1cGit0M',
    date: 'Hace 2 días',
    tilt: 1
  },
  {
    id: 'review-2',
    name: 'David K.',
    findUsMethod: 'Walk-in by chance',
    triedProduct: "Nana's Glazed Joy",
    sweetnessRating: 5,
    comment: 'Las mejores donas de toda la ciudad, sin duda alguna. La textura es como morder una nube flotante glaseada. Mis niños me las piden religiosamente cada domingo por la mañana perezosa.',
    imageFile: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD8DE0zlHR9nRsFjq74oES7uVyL9OEaZKJ2Pg3E3fv8umoRnl4aEqOTbZNpcB2rg6F57ChReutLEofpIFCoH598rjkqlHCdgqW-mmQmRg0S4eEu0vizGT9eWnwfGPoUd5cVCP7AXUbXSw00ISiddhotcRc2ex8YrTF2tofqhl7UJo1fCvyFnS7TND13-UR37j2IYdhahxFLncxbOcieQEvqT2Ks10wg1fKojTcmJKzbfvsUKErg0vstvboOGIP42sQGwzm4zs1nABk',
    date: 'Hace 5 días',
    tilt: -2
  }
];
